server:
  port: 8081
  servlet:
    context-path: /

spring:

  #dubbo
  dubbo:
    #d服务名称
    application: manange-web
    #zookeeper
    registry:
      #注册中心的地址
      address: 192.168.153.128:2181
      #注册中心的协议
      protocol: zookeeper
    #协议名
    protocol:
      name: dubbo
    #服务扫描路径
    base-package: com.itianfen.gmall
    consumer:
      check: false
      timeout: 60000
logging:
  level:
    root: info
