server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///gmall?serverTimezone=UTC
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.itianfen.gmall.user.bean

logging:
  level:
    com.itianfen.gmall.user.mapper: debug
mapper:
  i-d-e-n-t-i-t-y: MYSQL
